# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complex.proto

require 'google/protobuf'


descriptor_data = "\n\rcomplex.proto\x12\x08showcase\"\x9c\x04\n\x07Profile\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12 \n\x06status\x18\x03 \x01(\x0e\x32\x10.showcase.Status\x12\x42\n\x11\x63ustom_attributes\x18\x04 \x03(\x0b\x32\'.showcase.Profile.CustomAttributesEntry\x12$\n\x04role\x18\x05 \x01(\x0e\x32\x16.showcase.Profile.Role\x12\x0f\n\x05\x65mail\x18\x06 \x01(\tH\x00\x12\x0f\n\x05phone\x18\x07 \x01(\tH\x00\x12,\n\x08settings\x18\x08 \x01(\x0b\x32\x1a.showcase.Profile.Settings\x1a\x37\n\x15\x43ustomAttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x9d\x01\n\x08Settings\x12\x15\n\rnotifications\x18\x01 \x01(\x08\x12\x0e\n\x06locale\x18\x02 \x01(\t\x12\x33\n\x07privacy\x18\x03 \x01(\x0b\x32\".showcase.Profile.Settings.Privacy\x1a\x35\n\x07Privacy\x12\x16\n\x0epublic_profile\x18\x01 \x01(\x08\x12\x12\n\nshow_email\x18\x02 \x01(\x08\"7\n\x04Role\x12\x10\n\x0cROLE_UNKNOWN\x10\x00\x12\x0e\n\nROLE_ADMIN\x10\x01\x12\r\n\tROLE_USER\x10\x02\x42\t\n\x07\x63ontact\"\x1f\n\x11GetProfileRequest\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x13ListProfilesRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\":\n\x14UpdateProfileRequest\x12\"\n\x07profile\x18\x01 \x01(\x0b\x32\x11.showcase.Profile\"/\n\x16UpdateProfilesResponse\x12\x15\n\rupdated_count\x18\x01 \x01(\x05*D\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x11\n\rSTATUS_ACTIVE\x10\x01\x12\x13\n\x0fSTATUS_INACTIVE\x10\x02\x32\xac\x02\n\x0eProfileService\x12<\n\nGetProfile\x12\x1b.showcase.GetProfileRequest\x1a\x11.showcase.Profile\x12\x42\n\x0cListProfiles\x12\x1d.showcase.ListProfilesRequest\x1a\x11.showcase.Profile0\x01\x12T\n\x0eUpdateProfiles\x12\x1e.showcase.UpdateProfileRequest\x1a .showcase.UpdateProfilesResponse(\x01\x12\x42\n\x0cSyncProfiles\x12\x1b.showcase.GetProfileRequest\x1a\x11.showcase.Profile(\x01\x30\x01\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Showcase
  Profile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("showcase.Profile").msgclass
  Profile::Settings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("showcase.Profile.Settings").msgclass
  Profile::Settings::Privacy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("showcase.Profile.Settings.Privacy").msgclass
  Profile::Role = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("showcase.Profile.Role").enummodule
  GetProfileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("showcase.GetProfileRequest").msgclass
  ListProfilesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("showcase.ListProfilesRequest").msgclass
  UpdateProfileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("showcase.UpdateProfileRequest").msgclass
  UpdateProfilesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("showcase.UpdateProfilesResponse").msgclass
  Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("showcase.Status").enummodule
end
