# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: complex.proto for package 'showcase'

require 'grpc'
require 'complex_pb'

module Showcase
  module ProfileService
    # Service referencing the complex types
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'showcase.ProfileService'

      rpc :GetProfile, ::Showcase::GetProfileRequest, ::Showcase::Profile
      rpc :ListProfiles, ::Showcase::ListProfilesRequest, stream(::Showcase::Profile)
      rpc :UpdateProfiles, stream(::Showcase::UpdateProfileRequest), ::Showcase::UpdateProfilesResponse
      rpc :SyncProfiles, stream(::Showcase::GetProfileRequest), stream(::Showcase::Profile)
    end

    Stub = Service.rpc_stub_class
  end
end
