# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: dependency.proto for package 'dep'

require 'grpc'
require 'dependency_pb'

module Dep
  module DependencyService
    # Service that references types from complex.proto (cross-file dependency)
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'dep.DependencyService'

      rpc :ProcessProfile, ::Dep::ProcessRequest, ::Dep::ProcessResponse
    end

    Stub = Service.rpc_stub_class
  end
end
