# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dependency.proto

require 'google/protobuf'

require 'complex_pb'


descriptor_data = "\n\x10\x64\x65pendency.proto\x12\x03\x64\x65p\x1a\rcomplex.proto\"4\n\x0eProcessRequest\x12\"\n\x07profile\x18\x01 \x01(\x0b\x32\x11.showcase.Profile\"D\n\x0fProcessResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12 \n\x06status\x18\x02 \x01(\x0e\x32\x10.showcase.Status2P\n\x11\x44\x65pendencyService\x12;\n\x0eProcessProfile\x12\x13.dep.ProcessRequest\x1a\x14.dep.ProcessResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Dep
  ProcessRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dep.ProcessRequest").msgclass
  ProcessResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dep.ProcessResponse").msgclass
end
