# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum_only.proto

require 'google/protobuf'


descriptor_data = "\n\x0f\x65num_only.proto\x12\x08\x65numonly*q\n\x08Priority\x12\x14\n\x10PRIORITY_UNKNOWN\x10\x00\x12\x10\n\x0cPRIORITY_LOW\x10\x01\x12\x13\n\x0fPRIORITY_MEDIUM\x10\x02\x12\x11\n\rPRIORITY_HIGH\x10\x03\x12\x15\n\x11PRIORITY_CRITICAL\x10\x04*]\n\x08Severity\x12\x14\n\x10SEVERITY_UNKNOWN\x10\x00\x12\x11\n\rSEVERITY_INFO\x10\x01\x12\x14\n\x10SEVERITY_WARNING\x10\x02\x12\x12\n\x0eSEVERITY_ERROR\x10\x03\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Enumonly
  Priority = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("enumonly.Priority").enummodule
  Severity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("enumonly.Severity").enummodule
end
