# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

require 'google/protobuf'


descriptor_data = "\n\ntest.proto\x12\x04test\"\x1b\n\x0bTestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cTestResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2B\n\x0bTestService\x12\x33\n\nTestMethod\x12\x11.test.TestRequest\x1a\x12.test.TestResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Test
  TestRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.TestRequest").msgclass
  TestResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.TestResponse").msgclass
end
