# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test.proto for package 'test'

require 'grpc'
require 'test_pb'

module Test
  module TestService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'test.TestService'

      rpc :TestMethod, ::Test::TestRequest, ::Test::TestResponse
    end

    Stub = Service.rpc_stub_class
  end
end
