require 'grpc'
require 'google/protobuf'
require 'grpc/reflection/v1/reflection_services_pb'
require_relative 'grpc_reflection/version'
require_relative 'grpc_reflection/descriptor_registry'
require_relative 'grpc_reflection/service'
